name: Release Plugin

on:
    push:
        branches:
            - main
            - "feat/*"
            - "fix/*"
    workflow_dispatch:

permissions:
    contents: write
    issues: write
    pull-requests: write
    id-token: write
    pages: write
    deployments: write
    packages: read

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - run: corepack enable
            - run: yarn install --immutable && yarn info

            - name: Validate project
              run: yarn validate

            - name: Tag release
              run: yarn semantic-release

            - name: Upload Pages Artifact
              if: github.ref == 'refs/heads/main'
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist

    deploy_plugin_to_gh_pages:
        if: github.ref == 'refs/heads/main'
        needs: [release]
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
